image: rust:1.63

default:
  tags: [docker]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

stages:
  - build

build-and-test:
  stage: build
  script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-ext.galois.com" > ~/.git-credentials
    - cargo build --features bellman,sieve_ir,gf_scuttlebutt
    - cargo test --features bellman,sieve_ir,gf_scuttlebutt
    - cd deps/zk-circuit-builder/ && cargo test --features bellman,sieve_ir,gf_scuttlebutt
