image: rust:1.50

default:
  tags: [docker]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build-and-test:
  stage: build
  script:
    - cargo build
    - cargo test
    - cd deps/zk-circuit-builder/ && cargo test
