image: rust:1.63

default:
  tags: [docker]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

stages:
  - build

build-and-test:
  stage: build
  script:
    - cargo build
    - cargo test
    - cd deps/zk-circuit-builder/ && cargo test --features bellman,sieve_ir
