[package]
name = "cheesecloth"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["scale", "bellman"]
scale = ["scale_isa"]
bellman = ["zkinterface", "zkinterface_bellman"]
libsnark = ["zkinterface", "zkinterface-libsnark"]

[dependencies]
scale_isa = { optional = true, path = "../dialogue/scale_isa" }
zkinterface = { optional = true, version = "1.1.4", path = "../../qedit/zkinterface/rust" }
zkinterface_bellman = { optional = true, version = "1.1.4", path = "../../qedit/zkinterface-bellman" }
zkinterface-libsnark = { optional = true, version = "1.1.3", path = "../../qedit/zkinterface/cpp/libsnark-rust" }
bumpalo = "3.4"
colored = "1.9.3"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1"
serde_yaml = "0.8"