[package]
name = "cheesecloth"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["scale"]
scale = ["scale_isa"]

[dependencies]
scale_isa = { optional = true, path = "../dialogue/scale_isa" }
bumpalo = "3.4"
