[package]
name = "cheesecloth-derive-ir-typed"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.32"
syn = { version = "1.0.81", features = [ "full", "visit-mut" ] }
quote = "1.0.9"
